swagger: "2.0"
info:
  title: Bank Argent API documentation Transactions Module
  version: 1.0.0
host: localhost:3001
basePath: /api/v1 
schemes:
  - http
tags:
  - name: Transaction Module
    description: Operations about transactions, notes and categories

paths:
  /user/transactions:
    get:
      tags:
        - Transaction Module
      summary: Retrieve all transactions for the current month
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: query
          name: month
          type: string
          description: The month for which to retrieve the transactions (the current month)
          default: "2025-07"
          required: true
      responses:
        200:
          description: List of transactions for the specified month
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        401:
          description: Unauthorized (missing or invalid authentication)
        400:
          description: Invalid request
        500:
          description: Internal server error
    post:
      tags:
        - Transaction Module
      summary: Add a new transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Transaction"
          required: true
      responses:
        200:
          description: Transaction successfully created
        400:
          description: Invalid request (incorrect transaction data)
        401:
          description: Unauthorized (missing or invalid authentication)
        500:
          description: Internal server error
  
  /user/transaction/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Retrieve details of a specific transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
        - in: query
          name: month
          type: string
          required: true
          description: The month for which to retrieve the transaction
      responses:
        200:
          description: Transaction details
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Transaction not found
        500:
          description: Internal server error

  /user/transaction/{transactionId}/notes:
    post:
      tags:
        - Transaction Module
      summary: Add a note to a specific transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
          description: Unique transaction identifier
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Note"
          required: true
      responses:
        200:
          description: Note successfully added
        400:
          description: Invalid request
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Transaction not found
        500:
          description: Internal server error

  /user/transaction/{transactionId}/note/{noteId}:
    patch:
      tags:
        - Transaction Module
      summary: Edit a note on a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: path
          name: noteId
          type: string
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Note"
          required: true
      responses:
        200:
          description: Note successfully updated
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Note or transaction not found
        500:
          description: Internal server error

    delete:
      tags:
        - Transaction Module
      summary: Delete a note from a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: path
          name: noteId
          type: string
          required: true
      responses:
        200:
          description: Note successfully deleted
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Note or transaction not found
        500:
          description: Internal server error

  /user/transaction/{transactionId}/category:
    patch:
      tags:
        - Transaction Module
      summary: Edit the category of a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
          description: Unique transaction identifier
        - in: body
          name: body
          schema:
            type: object
            properties:
              category:
                type: string
                description: New transaction category
            required:
              - category
      responses:
        200:
          description: Category successfully updated
        400:
          description: Invalid request (missing or invalid category)
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Transaction not found
        500:
          description: Internal server error

  /user/transaction/categories:
    get:
      tags:
        - Transaction Module
      summary: Retrieve all available transaction categories
      responses:
        200:
          description: List of all transaction categories
          schema:
            type: array
            items:
              $ref: "#/definitions/Category"
        400:
          description: Invalid request
        401:
          description: Unauthorized (missing or invalid authentication)
        500:
          description: Internal server error
    post:
      tags:
        - Transaction Module
      summary: Add a new transaction category
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Category"
          required: true
      responses:
        200:
          description: Category successfully added
        400:
          description: Invalid request (missing or invalid category)
        401:
          description: Unauthorized (missing or invalid authentication)
        500:
          description: Internal server error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique transaction identifier
      month:
        type: string
        description: Month of the transaction
      date:
        type: string
        format: date
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        format: float
        description: Transaction amount
      balance:
        type: number
        format: float
        description: Account balance after the transaction
      categoryId:
        type: integer
        format: int32
        description: Identifier of the transaction category
      notes:
        type: array
        items:
          $ref: "#/definitions/Note"
        description: List of notes associated with the transaction
    required:
      - date
      - description
      - amount
      - balance
      - categoryId
    Category:
    type: object
    properties:
      id:
        type: string
        description: Unique category identifier
      category:
        type: string
        description: Name of the category
    required:
      - id
      - category
  Note:
    type: object
    properties:
      id:
        type: string
        description: Unique note identifier
      content:
        type: string
        description: Note text
      createdAt:
        type: string
        format: date-time
        description: Note creation date
      updatedAt:
        type: string
        format: date-time
        description: Note last update date
    required:
      - content
