swagger: "2.0"
info:
  title: Bank Argent API documentation User and Transaction Module
  version: 1.0.0
host: localhost:3001
basePath: /api/v1 
schemes:
  - http
tags:
  - name: Transaction Module
    description: Operations about transactions, notes and categories
  - name: User Module
    description: Operations about user authentication and profile
paths:
  /user/transactions:
    get:
      tags:
        - Transaction Module
      summary: Retrieve all transactions for the current month
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: query
          name: month
          type: string
          description: The month for which to retrieve the transactions (the current month)
          default: "2025-07"
          required: true
      responses:
        200:
          description: List of transactions for the specified month
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        401:
          description: Unauthorized (missing or invalid authentication)
        400:
          description: Invalid request
        500:
          description: Internal server error

  /user/transaction/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Retrieve details of a specific transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
        - in: query
          name: month
          type: string
          required: true
          description: The month for which to retrieve the transaction
      responses:
        200:
          description: Transaction details
          schema:
            $ref: "#/definitions/Transaction"
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Transaction not found
        500:
          description: Internal server error
    post:
      tags:
        - Transaction Module
      summary: Add a new transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Transaction"
          required: true
      responses:
        200:
          description: Transaction successfully created
        400:
          description: Invalid request (incorrect transaction data)
        401:
          description: Unauthorized (missing or invalid authentication)
        500:
          description: Internal server error

  /user/transaction/{transactionId}/notes:
    get:
      tags:
        - Transaction Module
      summary: Retrieve all notes for a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
          description: Transaction identifier
      responses:
        200:
          description: List of notes for the transaction
          schema:
            type: array
            items:
              $ref: "#/definitions/Note"
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Transaction not found
        500:
          description: Internal server error

    post:
      tags:
        - Transaction Module
      summary: Add a note to a specific transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
          description: Unique transaction identifier
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Note"
          required: true
      responses:
        200:
          description: Note successfully added
        400:
          description: Invalid request
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Transaction not found
        500:
          description: Internal server error

  /user/transaction/{transactionId}/notes/{noteId}:
    patch:
      tags:
        - Transaction Module
      summary: Edit a note on a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: path
          name: noteId
          type: string
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Note"
          required: true
      responses:
        200:
          description: Note successfully updated
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Note or transaction not found
        500:
          description: Internal server error

    delete:
      tags:
        - Transaction Module
      summary: Delete a note from a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
        - in: path
          name: noteId
          type: string
          required: true
      responses:
        200:
          description: Note successfully deleted
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Note or transaction not found
        500:
          description: Internal server error

  /user/transaction/{transactionId}/category:
    patch:
      tags:
        - Transaction Module
      summary: Edit the category of a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: path
          name: transactionId
          type: string
          required: true
          description: Unique transaction identifier
        - in: body
          name: body
          schema:
            type: object
            properties:
              category:
                type: string
                description: New transaction category
            required:
              - category
      responses:
        200:
          description: Category successfully updated
        400:
          description: Invalid request (missing or invalid category)
        401:
          description: Unauthorized (missing or invalid authentication)
        404:
          description: Transaction not found
        500:
          description: Internal server error

  /user/transaction/categories:
    get:
      tags:
        - Transaction Module
      summary: Retrieve all available transaction categories
      responses:
        200:
          description: List of all transaction categories
          schema:
            type: array
            items:
              $ref: "#/definitions/Category"
        400:
          description: Invalid request
        401:
          description: Unauthorized (missing or invalid authentication)
        500:
          description: Internal server error
    post:
      tags:
        - Transaction Module
      summary: Add a new transaction category
      parameters:
        - in: header
          name: Authorization
          type: string
          description: JWT token for authentication
          required: true
        - in: body
          name: body
          schema:
            $ref: "#/definitions/Category"
          required: true
      responses:
        200:
          description: Category successfully added
        400:
          description: Invalid request (missing or invalid category)
        401:
          description: Unauthorized (missing or invalid authentication)
        500:
          description: Internal server error

  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error 
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique transaction identifier
      month:
        type: string
        description: Month of the transaction
      date:
        type: string
        format: date
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        format: float
        description: Transaction amount
      balance:
        type: number
        format: float
        description: Account balance after the transaction
      categoryId:
        type: integer
        format: int32
        description: Identifier of the transaction category
      notes:
        type: array
        items:
          $ref: "#/definitions/Note"
        description: List of notes associated with the transaction
    required:
      - date
      - description
      - amount
      - balance
      - categoryId
    Category:
    type: object
    properties:
      id:
        type: string
        description: Unique category identifier
      category:
        type: string
        description: Name of the category
    required:
      - id
      - category
  Note:
    type: object
    properties:
      id:
        type: string
        description: Unique note identifier
      content:
        type: string
        description: Note text
      createdAt:
        type: string
        format: date-time
        description: Note creation date
      updatedAt:
        type: string
        format: date-time
        description: Note last update date
    required:
      - content
  User:
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
      firstName:
        type: string
        description: User first name
      lastName:
        type: string
        description: User last name
  Login:
    properties:
      email:
        type: string
        description: User email
      password:
        type: string
        description: User password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
        description: User first name
      lastName:
        type: string
        description: User last name
